### ISSUE TITLE
Plugin does not start though activated

### ISSUE THREAD

**Issue by betamigo98** [JohnTheGr8/Flow.Plugin.Bang#1]
Hello,
I tried the Bang flow plugin with different keyword activation but couldn't  use it.
I really tried to follow the exact same process as shown in the documentation (video) but without result.
I checked the [file related to duckduckgo APIs](https://github.com/JohnTheGr8/Flow.Plugin.Bang/blob/main/src/DuckDuckGoApi.fs) and some of the [plugin code](https://github.com/JohnTheGr8/Flow.Plugin.Bang/blob/main/src/Plugin.fs), but no idea what to look for whatsoever action to do.

The first picture show that Bang plugin recommendation does work, the second that it goes on with a blank bar when entering a bang. 

Any suggest as for the spacing between the keyword, the bang and the query?
Do I need a duckduckgo profile?
Thanks

![image](https://user-images.githubusercontent.com/105124171/167468149-0bf094d1-4043-4f6c-b200-41d44e7905b2.png)

![image](https://user-images.githubusercontent.com/105124171/167468191-8c085b0d-0d40-4267-81ff-28c205cce621.png)

**Comment by JohnTheGr8** [comment]
Hi, apologies for the late response.

The plugin checks the first typed word, **excluding the action keyword** (which is normally ignored because the plugin acts as a global plugin), and expects it to be a bang (starts with a `!`).

If you have changed the action keyword of the plugin to be `!b`, then I think you'll need to type `!b !gh flow-launcher` to search github...

**Comment by betamigo98** [comment]
Aaa so simple, sorry for the basic mistake done here.
In the end I switched back to the default setting without keyword ( `*`) so I got everything I want by pressing `!` as you suggest.
It does work perfectly.

Thanks
